# Base configs
baseurl: "https://kalunho.com/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Kalun Ho"
subtitle: ""
author: "Kalun Ho"
header:
 title: "Photography"
 subtitle: "by Kalun Ho"
footer:
 name: "Hey there, my name is Kalun"
 bio: "I love taking photos!"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/kalunho17\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/kalunhodotcom"
  linkedin: "https://www.linkedin.com/in/kalunho/"
  github: "https://github.com/kalunho17"
